"""empty message

Revision ID: 8291a0364cde
Revises: 
Create Date: 2022-04-29 23:31:57.327596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8291a0364cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CLIENT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=200), nullable=False),
    sa.Column('rua', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CLIENT')
    # ### end Alembic commands ###
