"""empty message

Revision ID: 946a8e6c4db8
Revises: ecf0ea9b4f42
Create Date: 2022-04-09 09:18:34.720522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '946a8e6c4db8'
down_revision = 'ecf0ea9b4f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PRODUCTS', 'last_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PRODUCTS', sa.Column('last_date', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
