"""empty message

Revision ID: ecf0ea9b4f42
Revises: 092f1cd05faa
Create Date: 2022-04-09 09:07:33.386068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecf0ea9b4f42'
down_revision = '092f1cd05faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PRODUCTS', sa.Column('last_date', sa.DateTime(), nullable=False))
    op.drop_column('PRODUCTS', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PRODUCTS', sa.Column('end_date', mysql.DATETIME(), nullable=False))
    op.drop_column('PRODUCTS', 'last_date')
    # ### end Alembic commands ###
